# Generated by Django 4.1.6 on 2024-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(),
        ),
    ]
