# Generated by Django 4.1.6 on 2024-01-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclothes', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
