# Generated by Django 4.1.6 on 2024-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclothes', '0006_coupon_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
