# Generated by Django 4.1.6 on 2023-08-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_cat_women_cat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='cat_slug',
        ),
        migrations.AddField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='women.category', to_field='slug'),
        ),
    ]
